
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.wilsoncys.compi1.javacraft.model.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int BOOL = 3;
  public static final int ARROW = 30;
  public static final int APPEND = 64;
  public static final int TUSTRIN = 71;
  public static final int CONST = 58;
  public static final int G_EQUALS = 16;
  public static final int ASSIGNMENT = 20;
  public static final int CHARAC = 4;
  public static final int DIVIDED = 11;
  public static final int DOUBLE = 44;
  public static final int STRUCT = 70;
  public static final int RAISED = 12;
  public static final int NOT = 36;
  public static final int MATCH = 26;
  public static final int DIFFERENT = 19;
  public static final int BRACK_R = 56;
  public static final int VAR = 57;
  public static final int UNEGATIVE = 37;
  public static final int BRACK_L = 55;
  public static final int CEROO = 31;
  public static final int KEY_CLOSE = 52;
  public static final int MOD = 13;
  public static final int ENTERO = 5;
  public static final int PLUS = 8;
  public static final int L_EQUALS = 17;
  public static final int WHILE = 27;
  public static final int DECIMAL = 6;
  public static final int CHAR = 46;
  public static final int BOOLEAN = 45;
  public static final int FIND = 67;
  public static final int DO = 21;
  public static final int FOR = 24;
  public static final int GREATER = 14;
  public static final int PAREN_CLOSE = 50;
  public static final int VOID = 48;
  public static final int RETURN = 69;
  public static final int ELSE = 23;
  public static final int BREAK = 25;
  public static final int DOT = 63;
  public static final int INT = 43;
  public static final int LENGTH = 66;
  public static final int KEY_OPEN = 51;
  public static final int EOF = 0;
  public static final int SEMICOLON = 53;
  public static final int DEFAULT = 29;
  public static final int PRINT = 42;
  public static final int START_W = 60;
  public static final int UNNO = 32;
  public static final int MINUS = 9;
  public static final int OR = 33;
  public static final int error = 1;
  public static final int CONTINUE = 28;
  public static final int LIST = 61;
  public static final int IF = 22;
  public static final int ID = 7;
  public static final int MINUSMINUS = 41;
  public static final int CAST = 39;
  public static final int COLON = 59;
  public static final int PLUSPLUS = 40;
  public static final int CADENA = 2;
  public static final int NEW = 62;
  public static final int PAREN_OPEN = 49;
  public static final int STRING = 47;
  public static final int LESS = 15;
  public static final int ROUND = 68;
  public static final int AND = 34;
  public static final int POINTS = 54;
  public static final int UMINUS = 38;
  public static final int REMOVE = 65;
  public static final int XOR = 35;
  public static final int EQUALS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "BOOL",
  "CHARAC",
  "ENTERO",
  "DECIMAL",
  "ID",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDED",
  "RAISED",
  "MOD",
  "GREATER",
  "LESS",
  "G_EQUALS",
  "L_EQUALS",
  "EQUALS",
  "DIFFERENT",
  "ASSIGNMENT",
  "DO",
  "IF",
  "ELSE",
  "FOR",
  "BREAK",
  "MATCH",
  "WHILE",
  "CONTINUE",
  "DEFAULT",
  "ARROW",
  "CEROO",
  "UNNO",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "UNEGATIVE",
  "UMINUS",
  "CAST",
  "PLUSPLUS",
  "MINUSMINUS",
  "PRINT",
  "INT",
  "DOUBLE",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "VOID",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "KEY_OPEN",
  "KEY_CLOSE",
  "SEMICOLON",
  "POINTS",
  "BRACK_L",
  "BRACK_R",
  "VAR",
  "CONST",
  "COLON",
  "START_W",
  "LIST",
  "NEW",
  "DOT",
  "APPEND",
  "REMOVE",
  "LENGTH",
  "FIND",
  "ROUND",
  "RETURN",
  "STRUCT",
  "TUSTRIN"
  };
}

